Address an old TODO: replace NO_TCMALLOC=On with SURELOG_USE_TCMALLOC…
chipsalliance/Surelog pull request #3505
Opened 2023-03-13 02:51 UTC by hzeller

…=Off

The negative logic (setting a variable to ON to get the OFF) behavior in the tcmalloc macro was always a bit mind-twisting. So now formulate it as positive logic with the common SURELOG_USE_* prefix.
The default for tcmalloc is still on, so the default should behave the same.

2023-03-13 02:52 UTC, hzeller commented
Also @timkpaine as you know cmake well and might need to be aware of the option change since you're working on some packages.

2023-03-13 17:23 UTC, hzeller commented
Adding both @hs-apotell and @alaindargelas for review. I don't expect anything to break directly, but this flag might be baked into your personal workflow, so this is mostly a heads-up.

2023-03-13 21:41 UTC, hzeller commented
Sounds good to me. So `SURELOG_WITH_TCMALLOC` would be the name ?
 (I think it is good to qualify the project in front so that it is clear in a multi-project linkage which is meant)

2023-03-13 22:17 UTC, hzeller commented
We prefix the other variables with `SURELOG_`, (four `SURELOG_USE_HOST_*` variables) wouldn't it be inconsistent to put surelog in the middle in `WITH_SURELOG_*` ?

I am not following typical cmake recommendations, so if it is a strong preference in cmake to use `WITH_` as the prefix, then of course we should use `WITH_SURELOG_TCMALLOC`.

2023-03-13 23:01 UTC, alaindargelas commented
@hzeller you have a deterministic failure with this PR, I rerun the failed test and they fail again.
Please address (Or @hs-apotell since the failure only shows on Windows platform).

2023-03-13 23:16 UTC, timkpaine commented
Arrow mixes `WITH`, `USE`, and <empty>  https://github.com/apache/arrow/blob/main/cpp/CMakeLists.txt#L660

2023-03-14 21:45 UTC, alaindargelas requested changes
@hzeller @hs-apotell, this PR fails the Windows release target.

2023-03-15 04:58 UTC, hzeller commented on .github/workflows/main.yml
> +        set ADDITIONAL_CMAKE_OPTIONS="-DPython3_ROOT_DIR=%pythonLocation% -DSURELOG_WITH_TCMALLOC=Off"
Is this the correct way to quote environment variables with spaces @hs-apotell ?

2023-03-15 04:58 UTC, hzeller commented
Changed to `SURELOG_WITH_TCMALLOC`.

I have no idea what the problems with the includes are. Maybe I have not quoted the environment variables correctly on Windows ? I used double quotes there, but maybe that needs to be done differently on the Windows shell. Maybe @hs-apotell can help ?

2023-03-15 06:36 UTC, hzeller commented
I am now trying without quotes on the Windows environment variable

2023-03-15 15:33 UTC, hzeller commented on .github/workflows/main.yml
> +        set ADDITIONAL_CMAKE_OPTIONS="-DPython3_ROOT_DIR=%pythonLocation% -DSURELOG_WITH_TCMALLOC=Off"
Ok, so removing the quotes helped.

2023-03-15 23:39 UTC, merged